"""Initial migration - create users, companies, filings tables

Revision ID: 0ee978b95b1b
Revises: 
Create Date: 2025-06-22 02:05:11.415714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ee978b95b1b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('sic', sa.String(length=10), nullable=True),
    sa.Column('sic_description', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('state_of_incorporation', sa.String(length=2), nullable=True),
    sa.Column('fiscal_year_end', sa.String(length=4), nullable=True),
    sa.Column('business_address', sa.Text(), nullable=True),
    sa.Column('mailing_address', sa.Text(), nullable=True),
    sa.Column('business_phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('is_sp500', sa.Boolean(), nullable=False),
    sa.Column('is_nasdaq100', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_filing_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_index(op.f('ix_companies_cik'), 'companies', ['cik'], unique=True)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('tier', sa.Enum('FREE', 'PRO', name='usertier'), nullable=False),
    sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('daily_reports_count', sa.Integer(), nullable=True),
    sa.Column('daily_reports_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('filings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('accession_number', sa.String(length=25), nullable=False),
    sa.Column('filing_type', sa.Enum('FORM_10K', 'FORM_10Q', 'FORM_8K', 'FORM_S1', 'FORM_DEF14A', 'FORM_20F', name='filingtype'), nullable=False),
    sa.Column('filing_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('primary_doc_url', sa.String(length=500), nullable=True),
    sa.Column('primary_doc_description', sa.String(length=255), nullable=True),
    sa.Column('full_text_url', sa.String(length=500), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('management_tone', sa.Enum('OPTIMISTIC', 'CONFIDENT', 'NEUTRAL', 'CAUTIOUS', 'CONCERNED', name='managementtone'), nullable=True),
    sa.Column('tone_explanation', sa.Text(), nullable=True),
    sa.Column('key_tags', sa.JSON(), nullable=True),
    sa.Column('key_questions', sa.JSON(), nullable=True),
    sa.Column('key_quotes', sa.JSON(), nullable=True),
    sa.Column('financial_highlights', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'DOWNLOADING', 'PARSING', 'AI_PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus'), nullable=False),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('bullish_votes', sa.Integer(), nullable=True),
    sa.Column('neutral_votes', sa.Integer(), nullable=True),
    sa.Column('bearish_votes', sa.Integer(), nullable=True),
    sa.Column('is_amended', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_filings_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_filings'))
    )
    op.create_index(op.f('ix_filings_accession_number'), 'filings', ['accession_number'], unique=True)
    op.create_index(op.f('ix_filings_company_id'), 'filings', ['company_id'], unique=False)
    op.create_index(op.f('ix_filings_filing_date'), 'filings', ['filing_date'], unique=False)
    op.create_index(op.f('ix_filings_filing_type'), 'filings', ['filing_type'], unique=False)
    op.create_index(op.f('ix_filings_id'), 'filings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_filings_id'), table_name='filings')
    op.drop_index(op.f('ix_filings_filing_type'), table_name='filings')
    op.drop_index(op.f('ix_filings_filing_date'), table_name='filings')
    op.drop_index(op.f('ix_filings_company_id'), table_name='filings')
    op.drop_index(op.f('ix_filings_accession_number'), table_name='filings')
    op.drop_table('filings')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_cik'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
