"""create_watchlist_table

Revision ID: 5c0cc3fbd189
Revises: 22db71afcbf1
Create Date: 2025-07-09 17:31:03.608012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c0cc3fbd189'
down_revision: Union[str, None] = '22db71afcbf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_user_watchlist_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_watchlist_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_watchlist')),
    sa.UniqueConstraint('user_id', 'company_id', name='_user_company_uc')
    )
    op.create_index(op.f('ix_user_watchlist_company_id'), 'user_watchlist', ['company_id'], unique=False)
    op.create_index(op.f('ix_user_watchlist_id'), 'user_watchlist', ['id'], unique=False)
    op.create_index(op.f('ix_user_watchlist_user_id'), 'user_watchlist', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_watchlist_user_id'), table_name='user_watchlist')
    op.drop_index(op.f('ix_user_watchlist_id'), table_name='user_watchlist')
    op.drop_index(op.f('ix_user_watchlist_company_id'), table_name='user_watchlist')
    op.drop_table('user_watchlist')
    # ### end Alembic commands ###