"""Add comment votes and vote counts

Revision ID: e4df702f8ef1
Revises: 6657ca959f79
Create Date: 2025-07-12 21:20:26.880532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4df702f8ef1'
down_revision: Union[str, None] = '6657ca959f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.alter_column('companies', 'cik',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.create_index(op.f('ix_earnings_calendar_id'), 'earnings_calendar', ['id'], unique=False)
    op.drop_index('idx_user_filing_views_user_date', table_name='user_filing_views')
    op.drop_index('idx_user_filing_views_user_filing', table_name='user_filing_views')
    op.create_index(op.f('ix_user_filing_views_id'), 'user_filing_views', ['id'], unique=False)
    op.create_index(op.f('ix_user_votes_id'), 'user_votes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_votes_id'), table_name='user_votes')
    op.drop_index(op.f('ix_user_filing_views_id'), table_name='user_filing_views')
    op.create_index('idx_user_filing_views_user_filing', 'user_filing_views', ['user_id', 'filing_id'], unique=False)
    op.create_index('idx_user_filing_views_user_date', 'user_filing_views', ['user_id', 'view_date'], unique=False)
    op.drop_index(op.f('ix_earnings_calendar_id'), table_name='earnings_calendar')
    op.alter_column('companies', 'cik',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    # ### end Alembic commands ###
