"""Add filing specific data and chart data fields

Revision ID: e8aeb514912a
Revises: baaec9c96033
Create Date: 2025-07-14 16:52:06.863456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8aeb514912a'
down_revision: Union[str, None] = 'baaec9c96033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns for differentiated display
    op.add_column('filings', sa.Column('filing_specific_data', postgresql.JSON(astext_type=sa.Text()), nullable=True, server_default='{}'))
    op.add_column('filings', sa.Column('chart_data', postgresql.JSON(astext_type=sa.Text()), nullable=True, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the columns
    op.drop_column('filings', 'chart_data')
    op.drop_column('filings', 'filing_specific_data')
    # ### end Alembic commands ###