"""Day 8: Add earnings calendar table

Revision ID: faa940c31fb2
Revises: 0ee978b95b1b
Create Date: 2025-06-30 18:24:13.380225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faa940c31fb2'
down_revision: Union[str, None] = '0ee978b95b1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earnings_calendar',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('earnings_date', sa.Date(), nullable=False),
        sa.Column('earnings_time', sa.Enum('bmo', 'amc', 'tns', name='earningstime'), nullable=True),
        sa.Column('fiscal_quarter', sa.String(length=10), nullable=True),
        sa.Column('fiscal_year', sa.Integer(), nullable=True),
        sa.Column('eps_estimate', sa.Float(), nullable=True),
        sa.Column('revenue_estimate', sa.Float(), nullable=True),
        sa.Column('previous_eps', sa.Float(), nullable=True),
        sa.Column('previous_revenue', sa.Float(), nullable=True),
        sa.Column('is_confirmed', sa.Boolean(), nullable=True),
        sa.Column('source', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_earnings_calendar_company_id'), 'earnings_calendar', ['company_id'], unique=False)
    op.create_index(op.f('ix_earnings_calendar_earnings_date'), 'earnings_calendar', ['earnings_date'], unique=False)
    op.create_index(op.f('ix_earnings_calendar_id'), 'earnings_calendar', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_earnings_calendar_id'), table_name='earnings_calendar')
    op.drop_index(op.f('ix_earnings_calendar_earnings_date'), table_name='earnings_calendar')
    op.drop_index(op.f('ix_earnings_calendar_company_id'), table_name='earnings_calendar')
    op.drop_table('earnings_calendar')
    # Drop the enum type
    op.execute("DROP TYPE IF EXISTS earningstime")
    # ### end Alembic commands ###